name: Daily Noise Backfill

on:
  schedule:
    - cron: '30 8 * * *'   # daily at 08:30 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily backfill
        env:
          PYTHONUNBUFFERED: "1"  # 👈 forces real-time print output
          INFLUX_URL:    ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN:  ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG:    ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
          # Optional override for sensors:
          # SENSOR_IDS: "94735,94284,94696"
        run: |
          python backfill_noise_data.py
