name: Daily Noise Backfill

on:
  # Runs every day at 01:30 UTC (which is 03:30 CEST)
  schedule:
    - cron: '30 1 * * *'
  # Also allow manual runs
  workflow_dispatch:

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:

      # 1. Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the backfill script
      - name: Run daily backfill
        env:
          INFLUX_URL:   ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG:   ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET:${{ secrets.INFLUX_BUCKET }}
          # Optional: override SENSOR_IDS if needed
          # SENSOR_IDS: "94735,94284,..."  
        run: |
          python backfill_noise_data.py
