name: Generate Directory Index

on:
  push:
    paths:
      - 'noise-map/reports/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Directory Listing
        uses: gacts/directory-listing@v1
        with:
          target: './noise-map/reports'
          overwrite: true

      # Official GitHub Pages Upload steps
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.' # This uploads your whole repository folder structure

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
