- name: Commit and push reports
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"
    git add reports/
    git commit -m "Update weekly reports [skip ci]" || echo "No changes to commit"
    git push
