# .github/workflows/weekly-report.yml
name: Weekly Report

on:
  workflow_dispatch:   # run manually from Actions tab
  schedule:
    - cron: "0 6 * * 1"   # every Monday 06:00 UTC

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pandas matplotlib reportlab

      - name: Run report script
        run: |
          python noise-map/weekly_report.py

      - name: Upload report PDF
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report
          path: noise-map/reports/*.pdf
