name: Weekly Noise Reports

on:
  schedule:
    - cron: '30 5 * * 1'   # every Monday
  workflow_dispatch:

jobs:
  weekly-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly report generator
        env:
          INFLUX_URL:    ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN:  ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG:    ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
        run: |
          python weekly_report.py

      - name: Deploy reports to gh-pages-reports
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-reports
          publish_dir: ./reports
