# .github/workflows/weekly-report.yml
name: Weekly Report

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pandas matplotlib reportlab

      - name: Install dependencies
        run: |
          pip install requests pandas matplotlib reportlab influxdb-client

      - name: Run report script
        run: |
          python ./weekly_report.py

      - name: Upload reports (HTML + PNGs)
        uses: actions/upload-artifact@v4
        with:
          name: weekly-reports
          path: reports/**

