name: Weekly Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * MON"  # Runs every Monday at 06:00 UTC

jobs:
  weekly-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly report
        env:
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
          # Use secret if available, otherwise fall back to sensor_data
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET || 'sensor_data' }}
        run: python weekly_report.py
